apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriharish-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sriharish-springboot
  template:
    metadata:
      labels:
        app: sriharish-springboot
    spec:
      containers:
        - name: springboot
          image: sriharish86/sriharish-docker-demo:sriharish-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: sriharish-springboot
spec:
  type: NodePort
  ports:
    - port: 81
      targetPort: 8021
  selector:
    app: sriharish-springboot
